Imports System.IO
Imports System.Text
Imports System.Text.Json

Namespace Services.Scheduling

    ''' <summary>
    ''' Per-language-pair latency and quality baseline, generated by the benchmark tool.
    ''' The translation queue uses this profile to estimate completion times
    ''' and detect performance degradation.
    ''' </summary>
    Public Class LatencyProfile
        Public Property Timestamp As DateTime
        Public Property Concurrency As Integer
        Public Property TotalRequests As Integer
        Public Property OverallAvgLatencyMs As Double
        Public Property OverallP95LatencyMs As Long
        Public Property OverallReqPerSec As Double
        Public Property Pairs As Dictionary(Of String, PairLatency)

        Public Sub New()
            Pairs = New Dictionary(Of String, PairLatency)()
        End Sub

        ''' <summary>
        ''' Get the baseline average latency for a specific language pair.
        ''' Returns Nothing if no profile data exists for this pair.
        ''' </summary>
        Public Function GetPairLatency(sourceLang As String, targetLang As String) As PairLatency
            Dim key = $"{sourceLang}>{targetLang}"
            Dim result As PairLatency = Nothing
            Pairs.TryGetValue(key, result)
            Return result
        End Function

        ''' <summary>
        ''' Estimate how long a translation for this pair will take, in milliseconds.
        ''' Falls back to the overall average if the pair isn't profiled.
        ''' </summary>
        Public Function EstimateLatencyMs(sourceLang As String, targetLang As String) As Double
            Dim pair = GetPairLatency(sourceLang, targetLang)
            If pair IsNot Nothing Then Return pair.AvgLatencyMs
            Return OverallAvgLatencyMs
        End Function

        ' ── Persistence ──

        Private Shared ReadOnly ProfileFileName As String = "benchmark-profile.json"

        ''' <summary>Get the path to the profile file.</summary>
        Public Shared Function GetProfilePath() As String
            Return Path.Combine(AppDomain.CurrentDomain.BaseDirectory, ProfileFileName)
        End Function

        ''' <summary>Save the profile to disk.</summary>
        Public Sub Save()
            Try
                Dim opts As New JsonSerializerOptions With {
                    .WriteIndented = True,
                    .PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                }
                Dim json = JsonSerializer.Serialize(Me, opts)
                File.WriteAllText(GetProfilePath(), json, Encoding.UTF8)
            Catch ex As Exception
                Infrastructure.AppLogger.Log($"[WARN] Failed to save latency profile: {ex.Message}")
            End Try
        End Sub

        ''' <summary>Load the profile from disk. Returns Nothing if no profile exists.</summary>
        Public Shared Function Load() As LatencyProfile
            Try
                Dim path = GetProfilePath()
                If Not File.Exists(path) Then Return Nothing

                Dim json = File.ReadAllText(path, Encoding.UTF8)
                Dim opts As New JsonSerializerOptions With {
                    .PropertyNamingPolicy = JsonNamingPolicy.CamelCase
                }
                Return JsonSerializer.Deserialize(Of LatencyProfile)(json, opts)
            Catch ex As Exception
                Infrastructure.AppLogger.Log($"[WARN] Failed to load latency profile: {ex.Message}")
                Return Nothing
            End Try
        End Function
    End Class

    ''' <summary>Latency and quality baseline for a single language pair.</summary>
    Public Class PairLatency
        Public Property AvgLatencyMs As Double
        Public Property AvgQuality As Double
        Public Property SampleCount As Integer
    End Class

End Namespace
